# Generated by Django 6.0.7 on 2026-07-23 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('owner', 'Owner'), ('orphan', 'Orphan')], default='read', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='filesystem.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_permissions', to='users.user')),
            ],
            options={
                'db_table': 'directory_permissions',
                'constraints': [models.UniqueConstraint(fields=('directory', 'user'), name='uq_directory_permission')],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('owner', 'Owner'), ('orphan', 'Orphan')], default='read', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='filesystem.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to='users.user')),
            ],
            options={
                'db_table': 'file_permissions',
                'constraints': [models.UniqueConstraint(fields=('file', 'user'), name='uq_file_permission')],
            },
        ),
    ]
