# Generated by Django 6.0.7 on 2026-08-01 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0002_initial'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='filesystem.file'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='directorypermission',
            constraint=models.UniqueConstraint(fields=('directory', 'user'), name='uq_directory_permission'),
        ),
        migrations.AddConstraint(
            model_name='filepermission',
            constraint=models.UniqueConstraint(fields=('file', 'user'), name='uq_file_permission'),
        ),
    ]
