# Generated by Django 6.0.7 on 2026-07-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypermission',
            name='permission_level',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('owner', 'Owner'), ('orphan', 'Orphan')], default='read', max_length=50),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='permission_level',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('owner', 'Owner'), ('orphan', 'Orphan')], default='read', max_length=50),
        ),
    ]
