# Generated by Django 6.0.7 on 2026-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypermission',
            name='permission_level',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('owner', 'Owner'), ('orphan', 'Orphan')], max_length=25),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='permission_level',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('owner', 'Owner'), ('orphan', 'Orphan')], max_length=25),
        ),
    ]
