# Generated by Django 6.0.7 on 2026-07-23 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunkAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_chunk_associations',
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_directories', to='users.user')),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='filesystem.directory')),
            ],
            options={
                'db_table': 'directories',
            },
        ),
        migrations.CreateModel(
            name='DirectorySubdirectoryAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_associations', to='filesystem.directory')),
                ('parent_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_associations', to='filesystem.directory')),
            ],
            options={
                'db_table': 'directory_subdirectory_associations',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=1024)),
                ('tributary_path', models.CharField(max_length=1024)),
                ('checksum', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('version', models.IntegerField(default=1)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_files', to='users.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to='users.user')),
                ('parent_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filesystem.directory')),
                ('prev_version_file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filesystem.file')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='DirectoryFileAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_associations', to='filesystem.directory')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_associations', to='filesystem.file')),
            ],
            options={
                'db_table': 'directory_file_associations',
            },
        ),
    ]
