# Generated by Django 6.0.7 on 2026-08-01 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_directories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='filesystem.directory'),
        ),
        migrations.AddField(
            model_name='file',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filesystem.directory'),
        ),
        migrations.AddField(
            model_name='file',
            name='prev_version_file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filesystem.file'),
        ),
        migrations.AddField(
            model_name='filechunkassociation',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_associations', to='storage.chunk'),
        ),
        migrations.AddField(
            model_name='filechunkassociation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_associations', to='filesystem.file'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent_directory'), name='uq_directory_hierarchy_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent_directory'), name='uq_directory_file'),
        ),
        migrations.AddConstraint(
            model_name='filechunkassociation',
            constraint=models.UniqueConstraint(fields=('file', 'chunk'), name='uq_file_chunk'),
        ),
    ]
