# Generated by Django 6.0.7 on 2026-07-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunkassociation',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_associations', to='storage.chunk'),
        ),
        migrations.AddField(
            model_name='filechunkassociation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_associations', to='filesystem.file'),
        ),
        migrations.AddConstraint(
            model_name='directorysubdirectoryassociation',
            constraint=models.UniqueConstraint(fields=('parent_directory', 'child_directory'), name='uq_directory_hierarchy_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='directoryfileassociation',
            constraint=models.UniqueConstraint(fields=('directory', 'file'), name='uq_directory_file'),
        ),
        migrations.AddConstraint(
            model_name='filechunkassociation',
            constraint=models.UniqueConstraint(fields=('file', 'chunk'), name='uq_file_chunk'),
        ),
    ]
