# Generated by Django 6.0.7 on 2026-08-16 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directory',
            name='uq_directory_hierarchy_parent_child',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='uq_directory_file',
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'parent_directory'), name='uq_directory_hierarchy_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'parent_directory'), name='uq_directory_file'),
        ),
    ]
