# Generated by Django 6.0.7 on 2026-07-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_directories', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='filesystem.directory'),
        ),
        migrations.AddField(
            model_name='file',
            name='local_path',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filesystem.directory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='prev_version_file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filesystem.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='tributary_path',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=1024),
            preserve_default=False,
        ),
    ]
