# Generated by Django 6.0.7 on 2026-07-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directoryfileassociation',
            name='uq_directory_file',
        ),
        migrations.RemoveConstraint(
            model_name='directorysubdirectoryassociation',
            name='uq_directory_hierarchy_parent_child',
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent_directory'), name='uq_directory_hierarchy_parent_child', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent_directory'), name='uq_directory_file', nulls_distinct=False),
        ),
        migrations.RemoveField(
            model_name='directorysubdirectoryassociation',
            name='child_directory',
        ),
        migrations.RemoveField(
            model_name='directorysubdirectoryassociation',
            name='parent_directory',
        ),
        migrations.DeleteModel(
            name='DirectoryFileAssociation',
        ),
        migrations.DeleteModel(
            name='DirectorySubdirectoryAssociation',
        ),
    ]
