# Generated by Django 6.0.7 on 2026-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0003_remove_directoryfileassociation_uq_directory_file_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directory',
            name='uq_directory_hierarchy_parent_child',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='uq_directory_file',
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent_directory'), name='uq_directory_hierarchy_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'parent_directory'), name='uq_directory_file'),
        ),
    ]
