"""intial commit to create models

Revision ID: 0ff08b688d1e
Revises:
Create Date: 2026-07-18 18:21:45.284618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ff08b688d1e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("actual_size", sa.BigInteger(), nullable=False),
        sa.Column("stored_size", sa.BigInteger(), nullable=False),
        sa.Column("encryption_key_id", sa.String(), nullable=False),
        sa.Column("logical_offset", sa.BigInteger(), nullable=False),
        sa.Column("reference_count", sa.Integer(), nullable=False),
        sa.Column("current_replica_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "directories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.String(), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ONLINE", "OFFLINE", "MAINTENANCE", name="nodestatus"),
            nullable=False,
        ),
        sa.Column("total_storage", sa.Float(), nullable=False),
        sa.Column("used_storage", sa.Float(), nullable=False),
        sa.Column("remaining_storage", sa.Float(), nullable=False),
        sa.Column("rack_id", sa.String(), nullable=True),
        sa.Column(
            "cluster",
            sa.Enum(
                "NORTH_AMERICA",
                "EUROPE",
                "MIDDLE_EAST",
                "SEA",
                "SOUTH_AMERICA",
                "AFRICA",
                name="cluster",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip", "port", name="uq_node_ip_port"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="uq_user_username"),
    )
    op.create_table(
        "chunk_replicas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("replica_index", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "UPLOADING", "COMPLETED", "FAILED", name="chunkstatus"),
            nullable=False,
        ),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("last_verified", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chunk_id", "node_id", name="uq_chunk_replica_chunk_id_node_id"
        ),
    )
    op.create_table(
        "directory_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("directory_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "permission_level",
            sa.Enum("OWNER", "WRITE", "READ", name="permissionlevel"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["directory_id"],
            ["directories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("directory_id", "user_id", name="uq_directory_permission"),
    )
    op.create_table(
        "directory_subdirectory_associations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_directory_id", sa.UUID(), nullable=False),
        sa.Column("child_directory_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_directory_id"],
            ["directories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_directory_id"],
            ["directories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_directory_id",
            "child_directory_id",
            name="uq_directory_hierarchy_parent_child",
        ),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_modified_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_chunk_associations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id", "chunk_id", name="uq_file_chunk"),
    )
    op.create_table(
        "file_directory_associations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("directory_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["directory_id"],
            ["directories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id", "directory_id", name="uq_file_directory"),
    )
    op.create_table(
        "file_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "permission_level",
            sa.Enum("OWNER", "WRITE", "READ", name="permissionlevel"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id", "user_id", name="uq_file_permission"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_permissions")
    op.drop_table("file_directory_associations")
    op.drop_table("file_chunk_associations")
    op.drop_table("files")
    op.drop_table("directory_subdirectory_associations")
    op.drop_table("directory_permissions")
    op.drop_table("chunk_replicas")
    op.drop_table("users")
    op.drop_table("nodes")
    op.drop_table("directories")
    op.drop_table("chunks")
    # ### end Alembic commands ###
