# Generated by Django 6.0.7 on 2026-08-12 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0002_initial'),
        ('storage', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadchunk',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_chunks', to='storage.chunk'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_files', to='filesystem.file'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uploads.upload'),
        ),
        migrations.AddField(
            model_name='uploadchunk',
            name='upload_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.uploadfile'),
        ),
    ]
