# Generated by Django 6.0.7 on 2026-08-16 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
                ('actual_size', models.BigIntegerField()),
                ('stored_size', models.BigIntegerField()),
                ('encryption_key_id', models.CharField(max_length=255)),
                ('logical_offset', models.BigIntegerField()),
                ('reference_count', models.IntegerField(default=1)),
                ('replica_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chunks',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('last_heartbeat', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')])),
                ('total_storage', models.BigIntegerField()),
                ('used_storage', models.BigIntegerField()),
                ('remaining_storage', models.BigIntegerField()),
                ('rack_id', models.CharField(max_length=255, null=True)),
                ('cluster', models.CharField(choices=[('North America', 'North America'), ('Europe', 'Europe'), ('Middle East', 'Middle East'), ('Southeast Asia', 'Southeast Asia'), ('South America', 'South America'), ('Africa', 'Africa')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nodes',
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'port'), name='uq_node_ip_port')],
            },
        ),
        migrations.CreateModel(
            name='ChunkReplica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('replica_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='storage.chunk')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_replicas', to='storage.node')),
            ],
            options={
                'db_table': 'chunk_replicas',
                'constraints': [models.UniqueConstraint(fields=('chunk', 'node'), name='uq_chunk_replica_chunk_id_node_id')],
            },
        ),
    ]
