# Generated by Django 6.0.7 on 2026-07-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='file',
        ),
    ]
