# Generated by Django 6.0.7 on 2026-08-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='logical_offset',
        ),
    ]
